import type { Metadata } from "next";
// import localFont from "next/font/local";
import "../globals.css";
import Navbar from "./navbar";
import Sidebar from "./sidebar";

// const geistSans = localFont({
//   src: "../fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "../fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={' antialiased bg-gray-100 w-full'}
      >
        <Navbar />
        <div className="flex flex-row"> 
        <Sidebar />
        <div className="flex-grow">
          {children}
        </div>
        </div>
      </body>
    </html>
  );
}
